[package]
org = "ballerina"
name = "avro"
version = "@toml.version@"
authors = ["Ballerina"]
export=["avro"]
keywords = ["avro", "serialization", "deserialization", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerina-avro"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "avro-native"
version = "@toml.version@"
path = "../native/build/libs/avro-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.avro"
artifactId = "avro"
version = "@avro.version@"
path = "./lib/avro-@avro.version@.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "@jackson.version@"
path = "./lib/jackson-core-@jackson.version@.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "@jackson.version@"
path = "./lib/jackson-annotations-@jackson.version@.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "@jackson.version@"
path = "./lib/jackson-databind-@jackson.version@.jar"
