[package]
org = "ballerina"
name = "avro"
version = "0.1.0"
authors = ["Ballerina"]
export=["avro"]
keywords = ["avro"]
repository = "https://github.com/ballerina-platform/module-ballerina-avro"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "avro-native"
version = "0.1.0"
path = "../native/build/libs/avro-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "org.apache.avro"
artifactId = "avro"
version = "1.11.3"
path = "./lib/avro-1.11.3.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.17.0"
path = "./lib/jackson-core-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.17.0"
path = "./lib/jackson-annotations-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.17.0"
path = "./lib/jackson-databind-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-avro"
version = "2.17.0"
path = "./lib/jackson-dataformat-avro-2.17.0.jar"
