[package]
org = "ballerina"
name = "avro"
version = "1.1.1"
authors = ["Ballerina"]
export=["avro"]
keywords = ["avro", "serialization", "deserialization", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerina-avro"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "avro-native"
version = "1.1.1"
path = "../native/build/libs/avro-native-1.1.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.avro"
artifactId = "avro"
version = "1.11.4"
path = "./lib/avro-1.11.4.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.18.0"
path = "./lib/jackson-core-2.18.0.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.18.0"
path = "./lib/jackson-annotations-2.18.0.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.18.0"
path = "./lib/jackson-databind-2.18.0.jar"
